// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class Constants
{
	public static int DEMO_TIMER = 3000; // milliseconds
	public static double DEMO_MULTIPLIER = 1.3;
	// for testing purposes
	public static int MAX_LEVELS = 9;

	public static int MAX_POINTS = 10000; // 10000 seconds is just over 2.5 hours

	public static int TEXT_TIMEOUT_SECONDS = 3;

	public static int BORED_TIMEOUT = 5;

	public static int NUM_BORED = 5;
	public static Dictionary<string, string> DIALOG = new Dictionary<string, string> () {
		{"BORED_0", "Gosh I wonder what my family is up to..."},
		{"BORED_1", "I can't remember the last time I slept..."},
		{"BORED_2", "Just one more level..."},
		{"BORED_3", "I'm pretty sure it's impossible to beat this game..."},
		{"BORED_4", "I wonder if it's sunny outside..."}
	};
	public const string achievement_hit_level_15 = "CgkI9OuD2JANEAIQBA"; // <GPGSID>
    public const string leaderboard_points = "CgkI9OuD2JANEAIQEA"; // <GPGSID>
    public const string achievement_hit_level_65 = "CgkI9OuD2JANEAIQDQ"; // <GPGSID>
    public const string achievement_hit_level_50 = "CgkI9OuD2JANEAIQCw"; // <GPGSID>
    public const string achievement_barely_there = "CgkI9OuD2JANEAIQDw"; // <GPGSID>
    public const string achievement_hit_level_55 = "CgkI9OuD2JANEAIQDA"; // <GPGSID>
    public const string achievement_hit_level_2 = "CgkI9OuD2JANEAIQAQ"; // <GPGSID>
    public const string leaderboard_level = "CgkI9OuD2JANEAIQEQ"; // <GPGSID>
    public const string achievement_hit_level_5 = "CgkI9OuD2JANEAIQAg"; // <GPGSID>
    public const string achievement_hit_level_45 = "CgkI9OuD2JANEAIQCg"; // <GPGSID>
    public const string achievement_hit_level_30 = "CgkI9OuD2JANEAIQBw"; // <GPGSID>
    public const string achievement_hit_level_35 = "CgkI9OuD2JANEAIQCA"; // <GPGSID>
    public const string achievement_hit_level_20 = "CgkI9OuD2JANEAIQBQ"; // <GPGSID>
    public const string achievement_fast_clicker = "CgkI9OuD2JANEAIQDg"; // <GPGSID>
    public const string achievement_hit_level_25 = "CgkI9OuD2JANEAIQBg"; // <GPGSID>
    public const string achievement_hit_level_10 = "CgkI9OuD2JANEAIQAw"; // <GPGSID>
    public const string achievement_hit_level_40 = "CgkI9OuD2JANEAIQCQ"; // <GPGSID>

}

